#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EcuPlaticos")]
	public partial class DBADODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_Cliente(Tbl_Cliente instance);
    partial void UpdateTbl_Cliente(Tbl_Cliente instance);
    partial void DeleteTbl_Cliente(Tbl_Cliente instance);
    partial void InsertTbl_Persona(Tbl_Persona instance);
    partial void UpdateTbl_Persona(Tbl_Persona instance);
    partial void DeleteTbl_Persona(Tbl_Persona instance);
    partial void InsertTbl_Usuario(Tbl_Usuario instance);
    partial void UpdateTbl_Usuario(Tbl_Usuario instance);
    partial void DeleteTbl_Usuario(Tbl_Usuario instance);
    partial void InsertTbl_Producto(Tbl_Producto instance);
    partial void UpdateTbl_Producto(Tbl_Producto instance);
    partial void DeleteTbl_Producto(Tbl_Producto instance);
    partial void InsertTbl_Orden_Produccion(Tbl_Orden_Produccion instance);
    partial void UpdateTbl_Orden_Produccion(Tbl_Orden_Produccion instance);
    partial void DeleteTbl_Orden_Produccion(Tbl_Orden_Produccion instance);
    partial void InsertTbl_Rol(Tbl_Rol instance);
    partial void UpdateTbl_Rol(Tbl_Rol instance);
    partial void DeleteTbl_Rol(Tbl_Rol instance);
    #endregion
		
		public DBADODataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.EcuPlaticosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBADODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBADODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBADODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBADODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Cliente> Tbl_Cliente
		{
			get
			{
				return this.GetTable<Tbl_Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Persona> Tbl_Persona
		{
			get
			{
				return this.GetTable<Tbl_Persona>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this.GetTable<Tbl_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Producto> Tbl_Producto
		{
			get
			{
				return this.GetTable<Tbl_Producto>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Orden_Produccion> Tbl_Orden_Produccion
		{
			get
			{
				return this.GetTable<Tbl_Orden_Produccion>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Rol> Tbl_Rol
		{
			get
			{
				return this.GetTable<Tbl_Rol>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Cliente")]
	public partial class Tbl_Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cli_Id;
		
		private System.Nullable<int> _Cli_Per_Id;
		
		private string _Cli_Cargo;
		
		private System.Nullable<char> _Cli_Estado;
		
		private EntityRef<Tbl_Persona> _Tbl_Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCli_IdChanging(int value);
    partial void OnCli_IdChanged();
    partial void OnCli_Per_IdChanging(System.Nullable<int> value);
    partial void OnCli_Per_IdChanged();
    partial void OnCli_CargoChanging(string value);
    partial void OnCli_CargoChanged();
    partial void OnCli_EstadoChanging(System.Nullable<char> value);
    partial void OnCli_EstadoChanged();
    #endregion
		
		public Tbl_Cliente()
		{
			this._Tbl_Persona = default(EntityRef<Tbl_Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cli_Id
		{
			get
			{
				return this._Cli_Id;
			}
			set
			{
				if ((this._Cli_Id != value))
				{
					this.OnCli_IdChanging(value);
					this.SendPropertyChanging();
					this._Cli_Id = value;
					this.SendPropertyChanged("Cli_Id");
					this.OnCli_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Per_Id", DbType="Int")]
		public System.Nullable<int> Cli_Per_Id
		{
			get
			{
				return this._Cli_Per_Id;
			}
			set
			{
				if ((this._Cli_Per_Id != value))
				{
					if (this._Tbl_Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCli_Per_IdChanging(value);
					this.SendPropertyChanging();
					this._Cli_Per_Id = value;
					this.SendPropertyChanged("Cli_Per_Id");
					this.OnCli_Per_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Cargo", DbType="VarChar(30)")]
		public string Cli_Cargo
		{
			get
			{
				return this._Cli_Cargo;
			}
			set
			{
				if ((this._Cli_Cargo != value))
				{
					this.OnCli_CargoChanging(value);
					this.SendPropertyChanging();
					this._Cli_Cargo = value;
					this.SendPropertyChanged("Cli_Cargo");
					this.OnCli_CargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Estado", DbType="Char(1)")]
		public System.Nullable<char> Cli_Estado
		{
			get
			{
				return this._Cli_Estado;
			}
			set
			{
				if ((this._Cli_Estado != value))
				{
					this.OnCli_EstadoChanging(value);
					this.SendPropertyChanging();
					this._Cli_Estado = value;
					this.SendPropertyChanged("Cli_Estado");
					this.OnCli_EstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Persona_Tbl_Cliente", Storage="_Tbl_Persona", ThisKey="Cli_Per_Id", OtherKey="Per_Id", IsForeignKey=true)]
		public Tbl_Persona Tbl_Persona
		{
			get
			{
				return this._Tbl_Persona.Entity;
			}
			set
			{
				Tbl_Persona previousValue = this._Tbl_Persona.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Persona.Entity = null;
						previousValue.Tbl_Cliente.Remove(this);
					}
					this._Tbl_Persona.Entity = value;
					if ((value != null))
					{
						value.Tbl_Cliente.Add(this);
						this._Cli_Per_Id = value.Per_Id;
					}
					else
					{
						this._Cli_Per_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Persona")]
	public partial class Tbl_Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Per_Id;
		
		private string _Per_Nombre;
		
		private string _Per_Apellido_Materno;
		
		private string _Per_Apellido_Paterno;
		
		private string _Per_Cedula;
		
		private string _Per_Direccion;
		
		private string _Per_Telefono;
		
		private System.Nullable<char> _Per_Estado;
		
		private EntitySet<Tbl_Cliente> _Tbl_Cliente;
		
		private EntitySet<Tbl_Usuario> _Tbl_Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPer_IdChanging(int value);
    partial void OnPer_IdChanged();
    partial void OnPer_NombreChanging(string value);
    partial void OnPer_NombreChanged();
    partial void OnPer_Apellido_MaternoChanging(string value);
    partial void OnPer_Apellido_MaternoChanged();
    partial void OnPer_Apellido_PaternoChanging(string value);
    partial void OnPer_Apellido_PaternoChanged();
    partial void OnPer_CedulaChanging(string value);
    partial void OnPer_CedulaChanged();
    partial void OnPer_DireccionChanging(string value);
    partial void OnPer_DireccionChanged();
    partial void OnPer_TelefonoChanging(string value);
    partial void OnPer_TelefonoChanged();
    partial void OnPer_EstadoChanging(System.Nullable<char> value);
    partial void OnPer_EstadoChanged();
    #endregion
		
		public Tbl_Persona()
		{
			this._Tbl_Cliente = new EntitySet<Tbl_Cliente>(new Action<Tbl_Cliente>(this.attach_Tbl_Cliente), new Action<Tbl_Cliente>(this.detach_Tbl_Cliente));
			this._Tbl_Usuario = new EntitySet<Tbl_Usuario>(new Action<Tbl_Usuario>(this.attach_Tbl_Usuario), new Action<Tbl_Usuario>(this.detach_Tbl_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Per_Id
		{
			get
			{
				return this._Per_Id;
			}
			set
			{
				if ((this._Per_Id != value))
				{
					this.OnPer_IdChanging(value);
					this.SendPropertyChanging();
					this._Per_Id = value;
					this.SendPropertyChanged("Per_Id");
					this.OnPer_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Per_Nombre
		{
			get
			{
				return this._Per_Nombre;
			}
			set
			{
				if ((this._Per_Nombre != value))
				{
					this.OnPer_NombreChanging(value);
					this.SendPropertyChanging();
					this._Per_Nombre = value;
					this.SendPropertyChanged("Per_Nombre");
					this.OnPer_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per_Apellido_Materno", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Per_Apellido_Materno
		{
			get
			{
				return this._Per_Apellido_Materno;
			}
			set
			{
				if ((this._Per_Apellido_Materno != value))
				{
					this.OnPer_Apellido_MaternoChanging(value);
					this.SendPropertyChanging();
					this._Per_Apellido_Materno = value;
					this.SendPropertyChanged("Per_Apellido_Materno");
					this.OnPer_Apellido_MaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per_Apellido_Paterno", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Per_Apellido_Paterno
		{
			get
			{
				return this._Per_Apellido_Paterno;
			}
			set
			{
				if ((this._Per_Apellido_Paterno != value))
				{
					this.OnPer_Apellido_PaternoChanging(value);
					this.SendPropertyChanging();
					this._Per_Apellido_Paterno = value;
					this.SendPropertyChanged("Per_Apellido_Paterno");
					this.OnPer_Apellido_PaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Per_Cedula
		{
			get
			{
				return this._Per_Cedula;
			}
			set
			{
				if ((this._Per_Cedula != value))
				{
					this.OnPer_CedulaChanging(value);
					this.SendPropertyChanging();
					this._Per_Cedula = value;
					this.SendPropertyChanged("Per_Cedula");
					this.OnPer_CedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per_Direccion", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Per_Direccion
		{
			get
			{
				return this._Per_Direccion;
			}
			set
			{
				if ((this._Per_Direccion != value))
				{
					this.OnPer_DireccionChanging(value);
					this.SendPropertyChanging();
					this._Per_Direccion = value;
					this.SendPropertyChanged("Per_Direccion");
					this.OnPer_DireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per_Telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Per_Telefono
		{
			get
			{
				return this._Per_Telefono;
			}
			set
			{
				if ((this._Per_Telefono != value))
				{
					this.OnPer_TelefonoChanging(value);
					this.SendPropertyChanging();
					this._Per_Telefono = value;
					this.SendPropertyChanged("Per_Telefono");
					this.OnPer_TelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per_Estado", DbType="Char(1)")]
		public System.Nullable<char> Per_Estado
		{
			get
			{
				return this._Per_Estado;
			}
			set
			{
				if ((this._Per_Estado != value))
				{
					this.OnPer_EstadoChanging(value);
					this.SendPropertyChanging();
					this._Per_Estado = value;
					this.SendPropertyChanged("Per_Estado");
					this.OnPer_EstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Persona_Tbl_Cliente", Storage="_Tbl_Cliente", ThisKey="Per_Id", OtherKey="Cli_Per_Id")]
		public EntitySet<Tbl_Cliente> Tbl_Cliente
		{
			get
			{
				return this._Tbl_Cliente;
			}
			set
			{
				this._Tbl_Cliente.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Persona_Tbl_Usuario", Storage="_Tbl_Usuario", ThisKey="Per_Id", OtherKey="Usu_Per_Id")]
		public EntitySet<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this._Tbl_Usuario;
			}
			set
			{
				this._Tbl_Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Cliente(Tbl_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Persona = this;
		}
		
		private void detach_Tbl_Cliente(Tbl_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Persona = null;
		}
		
		private void attach_Tbl_Usuario(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Persona = this;
		}
		
		private void detach_Tbl_Usuario(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Usuario")]
	public partial class Tbl_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Usu_Id;
		
		private string _Usu_Nombre;
		
		private string _Usu_Contrasenia;
		
		private System.Nullable<int> _Usu_Per_Id;
		
		private System.Nullable<int> _Usu_Rol_Id;
		
		private char _Usu_Estado;
		
		private EntityRef<Tbl_Persona> _Tbl_Persona;
		
		private EntityRef<Tbl_Rol> _Tbl_Rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsu_IdChanging(int value);
    partial void OnUsu_IdChanged();
    partial void OnUsu_NombreChanging(string value);
    partial void OnUsu_NombreChanged();
    partial void OnUsu_ContraseniaChanging(string value);
    partial void OnUsu_ContraseniaChanged();
    partial void OnUsu_Per_IdChanging(System.Nullable<int> value);
    partial void OnUsu_Per_IdChanged();
    partial void OnUsu_Rol_IdChanging(System.Nullable<int> value);
    partial void OnUsu_Rol_IdChanged();
    partial void OnUsu_EstadoChanging(char value);
    partial void OnUsu_EstadoChanged();
    #endregion
		
		public Tbl_Usuario()
		{
			this._Tbl_Persona = default(EntityRef<Tbl_Persona>);
			this._Tbl_Rol = default(EntityRef<Tbl_Rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Usu_Id
		{
			get
			{
				return this._Usu_Id;
			}
			set
			{
				if ((this._Usu_Id != value))
				{
					this.OnUsu_IdChanging(value);
					this.SendPropertyChanging();
					this._Usu_Id = value;
					this.SendPropertyChanged("Usu_Id");
					this.OnUsu_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Usu_Nombre
		{
			get
			{
				return this._Usu_Nombre;
			}
			set
			{
				if ((this._Usu_Nombre != value))
				{
					this.OnUsu_NombreChanging(value);
					this.SendPropertyChanging();
					this._Usu_Nombre = value;
					this.SendPropertyChanged("Usu_Nombre");
					this.OnUsu_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_Contrasenia", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Usu_Contrasenia
		{
			get
			{
				return this._Usu_Contrasenia;
			}
			set
			{
				if ((this._Usu_Contrasenia != value))
				{
					this.OnUsu_ContraseniaChanging(value);
					this.SendPropertyChanging();
					this._Usu_Contrasenia = value;
					this.SendPropertyChanged("Usu_Contrasenia");
					this.OnUsu_ContraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_Per_Id", DbType="Int")]
		public System.Nullable<int> Usu_Per_Id
		{
			get
			{
				return this._Usu_Per_Id;
			}
			set
			{
				if ((this._Usu_Per_Id != value))
				{
					if (this._Tbl_Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsu_Per_IdChanging(value);
					this.SendPropertyChanging();
					this._Usu_Per_Id = value;
					this.SendPropertyChanged("Usu_Per_Id");
					this.OnUsu_Per_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_Rol_Id", DbType="Int")]
		public System.Nullable<int> Usu_Rol_Id
		{
			get
			{
				return this._Usu_Rol_Id;
			}
			set
			{
				if ((this._Usu_Rol_Id != value))
				{
					if (this._Tbl_Rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsu_Rol_IdChanging(value);
					this.SendPropertyChanging();
					this._Usu_Rol_Id = value;
					this.SendPropertyChanged("Usu_Rol_Id");
					this.OnUsu_Rol_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_Estado", DbType="Char(1) NOT NULL")]
		public char Usu_Estado
		{
			get
			{
				return this._Usu_Estado;
			}
			set
			{
				if ((this._Usu_Estado != value))
				{
					this.OnUsu_EstadoChanging(value);
					this.SendPropertyChanging();
					this._Usu_Estado = value;
					this.SendPropertyChanged("Usu_Estado");
					this.OnUsu_EstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Persona_Tbl_Usuario", Storage="_Tbl_Persona", ThisKey="Usu_Per_Id", OtherKey="Per_Id", IsForeignKey=true)]
		public Tbl_Persona Tbl_Persona
		{
			get
			{
				return this._Tbl_Persona.Entity;
			}
			set
			{
				Tbl_Persona previousValue = this._Tbl_Persona.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Persona.Entity = null;
						previousValue.Tbl_Usuario.Remove(this);
					}
					this._Tbl_Persona.Entity = value;
					if ((value != null))
					{
						value.Tbl_Usuario.Add(this);
						this._Usu_Per_Id = value.Per_Id;
					}
					else
					{
						this._Usu_Per_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Rol_Tbl_Usuario", Storage="_Tbl_Rol", ThisKey="Usu_Rol_Id", OtherKey="Rol_Id", IsForeignKey=true)]
		public Tbl_Rol Tbl_Rol
		{
			get
			{
				return this._Tbl_Rol.Entity;
			}
			set
			{
				Tbl_Rol previousValue = this._Tbl_Rol.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Rol.Entity = null;
						previousValue.Tbl_Usuario.Remove(this);
					}
					this._Tbl_Rol.Entity = value;
					if ((value != null))
					{
						value.Tbl_Usuario.Add(this);
						this._Usu_Rol_Id = value.Rol_Id;
					}
					else
					{
						this._Usu_Rol_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Producto")]
	public partial class Tbl_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pro_Id;
		
		private string _Pro_Nombre;
		
		private System.Nullable<int> _Pro_Orp_Id;
		
		private System.Nullable<char> _Pro_Estado;
		
		private EntityRef<Tbl_Orden_Produccion> _Tbl_Orden_Produccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPro_IdChanging(int value);
    partial void OnPro_IdChanged();
    partial void OnPro_NombreChanging(string value);
    partial void OnPro_NombreChanged();
    partial void OnPro_Orp_IdChanging(System.Nullable<int> value);
    partial void OnPro_Orp_IdChanged();
    partial void OnPro_EstadoChanging(System.Nullable<char> value);
    partial void OnPro_EstadoChanged();
    #endregion
		
		public Tbl_Producto()
		{
			this._Tbl_Orden_Produccion = default(EntityRef<Tbl_Orden_Produccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pro_Id
		{
			get
			{
				return this._Pro_Id;
			}
			set
			{
				if ((this._Pro_Id != value))
				{
					this.OnPro_IdChanging(value);
					this.SendPropertyChanging();
					this._Pro_Id = value;
					this.SendPropertyChanged("Pro_Id");
					this.OnPro_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Nombre", DbType="VarChar(30)")]
		public string Pro_Nombre
		{
			get
			{
				return this._Pro_Nombre;
			}
			set
			{
				if ((this._Pro_Nombre != value))
				{
					this.OnPro_NombreChanging(value);
					this.SendPropertyChanging();
					this._Pro_Nombre = value;
					this.SendPropertyChanged("Pro_Nombre");
					this.OnPro_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Orp_Id", DbType="Int")]
		public System.Nullable<int> Pro_Orp_Id
		{
			get
			{
				return this._Pro_Orp_Id;
			}
			set
			{
				if ((this._Pro_Orp_Id != value))
				{
					if (this._Tbl_Orden_Produccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPro_Orp_IdChanging(value);
					this.SendPropertyChanging();
					this._Pro_Orp_Id = value;
					this.SendPropertyChanged("Pro_Orp_Id");
					this.OnPro_Orp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Estado", DbType="Char(1)")]
		public System.Nullable<char> Pro_Estado
		{
			get
			{
				return this._Pro_Estado;
			}
			set
			{
				if ((this._Pro_Estado != value))
				{
					this.OnPro_EstadoChanging(value);
					this.SendPropertyChanging();
					this._Pro_Estado = value;
					this.SendPropertyChanged("Pro_Estado");
					this.OnPro_EstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Orden_Produccion_Tbl_Producto", Storage="_Tbl_Orden_Produccion", ThisKey="Pro_Orp_Id", OtherKey="Orp_Id", IsForeignKey=true)]
		public Tbl_Orden_Produccion Tbl_Orden_Produccion
		{
			get
			{
				return this._Tbl_Orden_Produccion.Entity;
			}
			set
			{
				Tbl_Orden_Produccion previousValue = this._Tbl_Orden_Produccion.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Orden_Produccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Orden_Produccion.Entity = null;
						previousValue.Tbl_Producto.Remove(this);
					}
					this._Tbl_Orden_Produccion.Entity = value;
					if ((value != null))
					{
						value.Tbl_Producto.Add(this);
						this._Pro_Orp_Id = value.Orp_Id;
					}
					else
					{
						this._Pro_Orp_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Orden_Produccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Orden_Produccion")]
	public partial class Tbl_Orden_Produccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Orp_Id;
		
		private string _Orp_Num_Orden;
		
		private System.Nullable<System.DateTime> _Orp_Fecha_Pedido;
		
		private System.Nullable<System.DateTime> _Orp_Fecha_Entrega;
		
		private System.Nullable<int> _Orp_Maq_Id;
		
		private string _Orp_Ancho_Burbuja;
		
		private System.Nullable<double> _Orp_Calibre;
		
		private string _Orp_Color;
		
		private string _Orp_Descripcion;
		
		private string _Orp_Tratados;
		
		private string _Orp_Taca;
		
		private string _Orp_Refilar;
		
		private System.Nullable<int> _Orp_Total_kg;
		
		private System.Nullable<int> _Orp_Orc_Id;
		
		private System.Nullable<char> _Orp_Estado;
		
		private EntitySet<Tbl_Producto> _Tbl_Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrp_IdChanging(int value);
    partial void OnOrp_IdChanged();
    partial void OnOrp_Num_OrdenChanging(string value);
    partial void OnOrp_Num_OrdenChanged();
    partial void OnOrp_Fecha_PedidoChanging(System.Nullable<System.DateTime> value);
    partial void OnOrp_Fecha_PedidoChanged();
    partial void OnOrp_Fecha_EntregaChanging(System.Nullable<System.DateTime> value);
    partial void OnOrp_Fecha_EntregaChanged();
    partial void OnOrp_Maq_IdChanging(System.Nullable<int> value);
    partial void OnOrp_Maq_IdChanged();
    partial void OnOrp_Ancho_BurbujaChanging(string value);
    partial void OnOrp_Ancho_BurbujaChanged();
    partial void OnOrp_CalibreChanging(System.Nullable<double> value);
    partial void OnOrp_CalibreChanged();
    partial void OnOrp_ColorChanging(string value);
    partial void OnOrp_ColorChanged();
    partial void OnOrp_DescripcionChanging(string value);
    partial void OnOrp_DescripcionChanged();
    partial void OnOrp_TratadosChanging(string value);
    partial void OnOrp_TratadosChanged();
    partial void OnOrp_TacaChanging(string value);
    partial void OnOrp_TacaChanged();
    partial void OnOrp_RefilarChanging(string value);
    partial void OnOrp_RefilarChanged();
    partial void OnOrp_Total_kgChanging(System.Nullable<int> value);
    partial void OnOrp_Total_kgChanged();
    partial void OnOrp_Orc_IdChanging(System.Nullable<int> value);
    partial void OnOrp_Orc_IdChanged();
    partial void OnOrp_EstadoChanging(System.Nullable<char> value);
    partial void OnOrp_EstadoChanged();
    #endregion
		
		public Tbl_Orden_Produccion()
		{
			this._Tbl_Producto = new EntitySet<Tbl_Producto>(new Action<Tbl_Producto>(this.attach_Tbl_Producto), new Action<Tbl_Producto>(this.detach_Tbl_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Orp_Id
		{
			get
			{
				return this._Orp_Id;
			}
			set
			{
				if ((this._Orp_Id != value))
				{
					this.OnOrp_IdChanging(value);
					this.SendPropertyChanging();
					this._Orp_Id = value;
					this.SendPropertyChanged("Orp_Id");
					this.OnOrp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Num_Orden", DbType="VarChar(8)")]
		public string Orp_Num_Orden
		{
			get
			{
				return this._Orp_Num_Orden;
			}
			set
			{
				if ((this._Orp_Num_Orden != value))
				{
					this.OnOrp_Num_OrdenChanging(value);
					this.SendPropertyChanging();
					this._Orp_Num_Orden = value;
					this.SendPropertyChanged("Orp_Num_Orden");
					this.OnOrp_Num_OrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Fecha_Pedido", DbType="Date")]
		public System.Nullable<System.DateTime> Orp_Fecha_Pedido
		{
			get
			{
				return this._Orp_Fecha_Pedido;
			}
			set
			{
				if ((this._Orp_Fecha_Pedido != value))
				{
					this.OnOrp_Fecha_PedidoChanging(value);
					this.SendPropertyChanging();
					this._Orp_Fecha_Pedido = value;
					this.SendPropertyChanged("Orp_Fecha_Pedido");
					this.OnOrp_Fecha_PedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Fecha_Entrega", DbType="Date")]
		public System.Nullable<System.DateTime> Orp_Fecha_Entrega
		{
			get
			{
				return this._Orp_Fecha_Entrega;
			}
			set
			{
				if ((this._Orp_Fecha_Entrega != value))
				{
					this.OnOrp_Fecha_EntregaChanging(value);
					this.SendPropertyChanging();
					this._Orp_Fecha_Entrega = value;
					this.SendPropertyChanged("Orp_Fecha_Entrega");
					this.OnOrp_Fecha_EntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Maq_Id", DbType="Int")]
		public System.Nullable<int> Orp_Maq_Id
		{
			get
			{
				return this._Orp_Maq_Id;
			}
			set
			{
				if ((this._Orp_Maq_Id != value))
				{
					this.OnOrp_Maq_IdChanging(value);
					this.SendPropertyChanging();
					this._Orp_Maq_Id = value;
					this.SendPropertyChanged("Orp_Maq_Id");
					this.OnOrp_Maq_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Ancho_Burbuja", DbType="VarChar(12)")]
		public string Orp_Ancho_Burbuja
		{
			get
			{
				return this._Orp_Ancho_Burbuja;
			}
			set
			{
				if ((this._Orp_Ancho_Burbuja != value))
				{
					this.OnOrp_Ancho_BurbujaChanging(value);
					this.SendPropertyChanging();
					this._Orp_Ancho_Burbuja = value;
					this.SendPropertyChanged("Orp_Ancho_Burbuja");
					this.OnOrp_Ancho_BurbujaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Calibre", DbType="Float")]
		public System.Nullable<double> Orp_Calibre
		{
			get
			{
				return this._Orp_Calibre;
			}
			set
			{
				if ((this._Orp_Calibre != value))
				{
					this.OnOrp_CalibreChanging(value);
					this.SendPropertyChanging();
					this._Orp_Calibre = value;
					this.SendPropertyChanged("Orp_Calibre");
					this.OnOrp_CalibreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Color", DbType="VarChar(20)")]
		public string Orp_Color
		{
			get
			{
				return this._Orp_Color;
			}
			set
			{
				if ((this._Orp_Color != value))
				{
					this.OnOrp_ColorChanging(value);
					this.SendPropertyChanging();
					this._Orp_Color = value;
					this.SendPropertyChanged("Orp_Color");
					this.OnOrp_ColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Descripcion", DbType="VarChar(50)")]
		public string Orp_Descripcion
		{
			get
			{
				return this._Orp_Descripcion;
			}
			set
			{
				if ((this._Orp_Descripcion != value))
				{
					this.OnOrp_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._Orp_Descripcion = value;
					this.SendPropertyChanged("Orp_Descripcion");
					this.OnOrp_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Tratados", DbType="VarChar(10)")]
		public string Orp_Tratados
		{
			get
			{
				return this._Orp_Tratados;
			}
			set
			{
				if ((this._Orp_Tratados != value))
				{
					this.OnOrp_TratadosChanging(value);
					this.SendPropertyChanging();
					this._Orp_Tratados = value;
					this.SendPropertyChanged("Orp_Tratados");
					this.OnOrp_TratadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Taca", DbType="VarChar(10)")]
		public string Orp_Taca
		{
			get
			{
				return this._Orp_Taca;
			}
			set
			{
				if ((this._Orp_Taca != value))
				{
					this.OnOrp_TacaChanging(value);
					this.SendPropertyChanging();
					this._Orp_Taca = value;
					this.SendPropertyChanged("Orp_Taca");
					this.OnOrp_TacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Refilar", DbType="VarChar(10)")]
		public string Orp_Refilar
		{
			get
			{
				return this._Orp_Refilar;
			}
			set
			{
				if ((this._Orp_Refilar != value))
				{
					this.OnOrp_RefilarChanging(value);
					this.SendPropertyChanging();
					this._Orp_Refilar = value;
					this.SendPropertyChanged("Orp_Refilar");
					this.OnOrp_RefilarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Total_kg", DbType="Int")]
		public System.Nullable<int> Orp_Total_kg
		{
			get
			{
				return this._Orp_Total_kg;
			}
			set
			{
				if ((this._Orp_Total_kg != value))
				{
					this.OnOrp_Total_kgChanging(value);
					this.SendPropertyChanging();
					this._Orp_Total_kg = value;
					this.SendPropertyChanged("Orp_Total_kg");
					this.OnOrp_Total_kgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Orc_Id", DbType="Int")]
		public System.Nullable<int> Orp_Orc_Id
		{
			get
			{
				return this._Orp_Orc_Id;
			}
			set
			{
				if ((this._Orp_Orc_Id != value))
				{
					this.OnOrp_Orc_IdChanging(value);
					this.SendPropertyChanging();
					this._Orp_Orc_Id = value;
					this.SendPropertyChanged("Orp_Orc_Id");
					this.OnOrp_Orc_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orp_Estado", DbType="Char(1)")]
		public System.Nullable<char> Orp_Estado
		{
			get
			{
				return this._Orp_Estado;
			}
			set
			{
				if ((this._Orp_Estado != value))
				{
					this.OnOrp_EstadoChanging(value);
					this.SendPropertyChanging();
					this._Orp_Estado = value;
					this.SendPropertyChanged("Orp_Estado");
					this.OnOrp_EstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Orden_Produccion_Tbl_Producto", Storage="_Tbl_Producto", ThisKey="Orp_Id", OtherKey="Pro_Orp_Id")]
		public EntitySet<Tbl_Producto> Tbl_Producto
		{
			get
			{
				return this._Tbl_Producto;
			}
			set
			{
				this._Tbl_Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Producto(Tbl_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Orden_Produccion = this;
		}
		
		private void detach_Tbl_Producto(Tbl_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Orden_Produccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Rol")]
	public partial class Tbl_Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Rol_Id;
		
		private string _Rol_Nombre;
		
		private string _Rol_Descripcion;
		
		private char _Rol_Estado;
		
		private EntitySet<Tbl_Usuario> _Tbl_Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRol_IdChanging(int value);
    partial void OnRol_IdChanged();
    partial void OnRol_NombreChanging(string value);
    partial void OnRol_NombreChanged();
    partial void OnRol_DescripcionChanging(string value);
    partial void OnRol_DescripcionChanged();
    partial void OnRol_EstadoChanging(char value);
    partial void OnRol_EstadoChanged();
    #endregion
		
		public Tbl_Rol()
		{
			this._Tbl_Usuario = new EntitySet<Tbl_Usuario>(new Action<Tbl_Usuario>(this.attach_Tbl_Usuario), new Action<Tbl_Usuario>(this.detach_Tbl_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Rol_Id
		{
			get
			{
				return this._Rol_Id;
			}
			set
			{
				if ((this._Rol_Id != value))
				{
					this.OnRol_IdChanging(value);
					this.SendPropertyChanging();
					this._Rol_Id = value;
					this.SendPropertyChanged("Rol_Id");
					this.OnRol_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Rol_Nombre
		{
			get
			{
				return this._Rol_Nombre;
			}
			set
			{
				if ((this._Rol_Nombre != value))
				{
					this.OnRol_NombreChanging(value);
					this.SendPropertyChanging();
					this._Rol_Nombre = value;
					this.SendPropertyChanged("Rol_Nombre");
					this.OnRol_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol_Descripcion", DbType="VarChar(100)")]
		public string Rol_Descripcion
		{
			get
			{
				return this._Rol_Descripcion;
			}
			set
			{
				if ((this._Rol_Descripcion != value))
				{
					this.OnRol_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._Rol_Descripcion = value;
					this.SendPropertyChanged("Rol_Descripcion");
					this.OnRol_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol_Estado", DbType="Char(1) NOT NULL")]
		public char Rol_Estado
		{
			get
			{
				return this._Rol_Estado;
			}
			set
			{
				if ((this._Rol_Estado != value))
				{
					this.OnRol_EstadoChanging(value);
					this.SendPropertyChanging();
					this._Rol_Estado = value;
					this.SendPropertyChanged("Rol_Estado");
					this.OnRol_EstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Rol_Tbl_Usuario", Storage="_Tbl_Usuario", ThisKey="Rol_Id", OtherKey="Usu_Rol_Id")]
		public EntitySet<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this._Tbl_Usuario;
			}
			set
			{
				this._Tbl_Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Usuario(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Rol = this;
		}
		
		private void detach_Tbl_Usuario(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Rol = null;
		}
	}
}
#pragma warning restore 1591
